In [4]:
exec(open('inc_notebook.py').read())

FileNotFoundError: [Errno 2] No such file or directory: 'inc_notebook.py'

In [3]:
#1. Each agent has its own memory 

In [5]:

import numpy as np

In [8]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [9]:
memory = np.arange(5)

In [10]:
memory[:-1] = memory[1:]

In [13]:
memory

array([1, 2, 3, 4, 2])

In [12]:
memory[-1]=2

In [17]:
np.random.choice(2, 10, p=[.2, .8])

array([1, 1, 1, 1, 1, 0, 1, 1, 1, 1], dtype=int64)

In [19]:
np.random.choice([1, 2, 3, 4, 5], 1)

array([5])